#!/usr/bin/env python3
"""Behavioral regression tests for generated Qt QML attribution."""
import hashlib
import importlib.util
import json
from pathlib import Path
import tempfile
import unittest

spec = importlib.util.spec_from_file_location('appimage_audit', Path(__file__).with_name('audit.py'))
audit = importlib.util.module_from_spec(spec)
spec.loader.exec_module(audit)


class QtAttributionTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.media = Path(temporary.name)
        self.prefix = self.media / 'prefix'
        self.prefix.mkdir()
        self.backend = self.file('lib/libQt6Example.so.6.11.2', b'checked vendor backend')
        self.file('qml/Builtin/Example/qmldir', b'module Builtin.Example\nstatic\nsystem\ntypeinfo types.qmltypes\n')
        self.file('qml/Builtin/Example/types.qmltypes', b'// This file was auto-generated by qmltyperegistrar.\nModule {}\n')
        self.file('lib/cmake/Qt6Example/Qt6ExampleTargets.cmake', b'''set_target_properties(Qt6::Example PROPERTIES
  _qt_qml_module_is_backing_target "TRUE"
  _qt_qml_module_installed_qmldir_path "qml/Builtin/Example/qmldir"
  _qt_qml_module_uri "Builtin.Example"
  _qt_sbom_spdx_id "SPDXRef-Example"
  _qt_sbom_spdx_v2_document_json_relative_path "sbom/qtbase-6.11.2.spdx.json"
  _qt_sbom_package_version "6.11.2"
)
''')
        self.document = {'name': 'qtbase', 'packages': [
            {'SPDXID': 'SPDXRef-Example', 'name': 'Example', 'versionInfo': '6.11.2',
             'licenseConcluded': 'LGPL-3.0-only'}],
            'files': [{'SPDXID': 'SPDXRef-Backend', 'fileName': './lib/libQt6Example.so.6.11.2',
                       'licenseConcluded': 'LGPL-3.0-only',
                       'checksums': [{'algorithm': 'SHA256', 'checksumValue': hashlib.sha256(self.backend.read_bytes()).hexdigest()}]}],
            'relationships': [{'spdxElementId': 'SPDXRef-Example', 'relatedSpdxElement': 'SPDXRef-Backend',
                               'relationshipType': 'CONTAINS'}]}
        self.documents()

    def file(self, relative, content):
        path = self.prefix / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(content)
        return path

    def documents(self):
        for name in ('qtbase', 'qtdeclarative', 'qtsvg', 'qtshadertools'):
            document = self.document if name == 'qtbase' else {'name': name, 'packages': [], 'files': [], 'relationships': []}
            self.file('sbom/' + name + '-6.11.2.spdx.json', json.dumps(document).encode())

    def owners(self):
        return {'usr/' + source: {'owner': 'media', 'source': source}
                for source in ('qml/Builtin/Example/qmldir', 'qml/Builtin/Example/types.qmltypes')}

    def test_builtin_metadata_uses_backend_component_without_inventing_file_terms(self):
        owners = self.owners()
        audit.qt_evidence(self.media, owners, self.media)
        for owner in owners.values():
            component = owner['components'][0]
            self.assertEqual(component['component_id'], 'qt:qtbase')
            self.assertIsNone(component['license_expression'])
            self.assertEqual(component['module_license_expression'], 'LGPL-3.0-only')
            self.assertEqual(component['evidence']['Qt_vendor_version'], '6.11.2')
            self.assertEqual(component['evidence']['package']['SPDXID'], 'SPDXRef-Example')
            self.assertEqual(component['evidence']['backend_files'][0]['file_spdx_id'], 'SPDXRef-Backend')

    def test_generated_terms_stay_unresolved_in_per_file_registry(self):
        owners = self.owners()
        qt = audit.qt_evidence(self.media, owners, self.media)
        providers = {'media': self.media}
        documents = {
            'app': {'crates': [], 'binary': {'rust_standard_library': {'archives': []}, 'direct_objects': []}},
            'runtime': {'components': []},
            'stage': {'packages': []}}
        for name, document in documents.items():
            directory = self.media / name
            directory.mkdir()
            providers[name] = directory
            filename = 'ubuntu-sources.json' if name == 'stage' else 'manifest.json'
            (directory / filename).write_text(json.dumps(document))
        registry, _, _ = audit.load('components').registry(providers, owners, qt, {'components': []}, audit.stage.digest)
        for owner in owners.values():
            component = owner['components'][0]
            self.assertEqual(component['source_component_id'], 'qt:qtbase')
            self.assertIsNone(component['selected_terms'])
            self.assertFalse(component['terms_resolved'])
            self.assertEqual(registry[component['component_id']], component)

    def test_unrelated_vendor_backend_does_not_attribute_builtin_module(self):
        self.document['relationships'] = []
        self.documents()
        with self.assertRaisesRegex(ValueError, 'QML module lacks vendor'):
            audit.qt_evidence(self.media, self.owners(), self.media)

    def test_changed_vendor_backend_remains_rejected(self):
        self.backend.write_bytes(b'changed backend')
        with self.assertRaisesRegex(ValueError, 'Qt vendor SBOM checksum mismatch'):
            audit.qt_evidence(self.media, self.owners(), self.media)


if __name__ == '__main__':
    unittest.main()
